fail_fast: true
default_stages: [commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: mixed-line-ending
      files: '.*\.sh'
      args: [--fix=lf]
    - id: check-added-large-files
    - id: check-yaml
    - id: check-json
    - id: debug-statements
    - id: double-quote-string-fixer
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    verbose: true
    entry: bash -c 'mypy "$@" || true'
    args: [--ignore-missing-imports]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.6
  hooks:
    - id: ruff
      args: [ --fix, --select, I]
    - id: ruff-format
