repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: mixed-line-ending
      files: '.*\.sh'
      args: [--fix=lf]
    - id: check-yaml
    - id: check-json
    - id: debug-statements
    - id: double-quote-string-fixer
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
- repo: local
  hooks:
    - id: yapf
      name: yapf-formatter
      entry: yapf
      args: [--style=yapf]
      language: system
      pass_filenames: false
      always_run: true
