# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.app', '--build-arg', 'PROJECT_ID=$PROJECT_ID', '--build-arg', 'PROJECT_NAME=$_PROJECT_NAME', '-t', 'gcr.io/$PROJECT_ID/$_PROJECT_NAME', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.job', '--build-arg', 'PROJECT_ID=$PROJECT_ID', '--build-arg', 'PROJECT_NAME=$_PROJECT_NAME', '-t', 'gcr.io/$PROJECT_ID/${_PROJECT_NAME}_job', '.']

images:
- 'gcr.io/$PROJECT_ID/$_PROJECT_NAME'
- 'gcr.io/$PROJECT_ID/${_PROJECT_NAME}_job'

substitutions:
  _PROJECT_NAME: 'Default Project Name'
