auth:
  client_id:
  client_secret:
  developer_token:
  login_customer_id:
  project_id:
  project_number:
  refresh_token:
  use_proto_plus: true
bigquery:
  dataset: ac_protect
  last_trigger_log: last_trigger_log
collectors:
  collector_ga4:
    properties: []
  collector_gads:
    customer_id: null
    start_date: 10
    version: v15
  collector_app_store: []
  collector_play_store: []
