auth:
  client_id:
  client_secret:
  refresh_token:
  login_customer_id:
  developer_token:
  use_proto_plus: true
  project_number:
  project_id:
collectors:
  ga4:
    properties: []
  gads:
    version: "v15"
    customer_id:
    start_date: 10
bigquery:
  dataset:
  last_trigger_log: last_trigger_log
apps:
  app_name_1:
    rules:
      version_events: []
    alerts:
      emails: []
  app_name_2:
    rules: []
    alerts: []
